source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftChan_Example', :exclusive => true do
  pod "SwiftChan", :path => "../"
end

target 'SwiftChan_Tests', :exclusive => true do
  pod 'Quick'
  pod 'Nimble'
end
